# -*- coding: utf-8 -*-
"""Prompt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T15TpIkD2s8JVUxtJdSiS29pcw5ZYIuN
"""

!pip install transformers datasets scikit-learn pandas torch

import pandas as pd

# Upload your file in Colab or mount drive
df = pd.read_csv('/content/merged_dataset.csv')

df.head()

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['complexity'] = le.fit_transform(df['complexity'])

num_labels = df['complexity'].nunique()
print("Number of classes:", num_labels)

from sklearn.model_selection import train_test_split

train_df, val_df = train_test_split(df, test_size=0.1, stratify=df['complexity'], random_state=42)

from datasets import Dataset

train_dataset = Dataset.from_pandas(train_df)
val_dataset = Dataset.from_pandas(val_df)

from transformers import AutoTokenizer

model_name = "bert-base-uncased"
tokenizer = AutoTokenizer.from_pretrained(model_name)

def tokenize(example):
    return tokenizer(example['prompt'], truncation=True, padding='max_length', max_length=128)

train_dataset = train_dataset.map(tokenize, batched=True)
val_dataset = val_dataset.map(tokenize, batched=True)

# Rename complexity to labels so the model can compute loss automatically
train_dataset = train_dataset.rename_column('complexity', 'labels')
val_dataset = val_dataset.rename_column('complexity', 'labels')

train_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])
val_dataset.set_format(type='torch', columns=['input_ids', 'attention_mask', 'labels'])

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    model_name,
    num_labels=num_labels
)

from transformers import TrainingArguments

training_args = TrainingArguments(
    output_dir="./results",
    eval_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    report_to="none",
    load_best_model_at_end=True
)

import numpy as np
from sklearn.metrics import accuracy_score, f1_score

def compute_metrics(eval_pred):
    logits, labels = eval_pred
    preds = np.argmax(logits, axis=1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "f1": f1_score(labels, preds, average="weighted")
    }

from transformers import Trainer

# Re-initializing the trainer to pick up the renamed 'labels' column in the datasets
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=train_dataset,
    eval_dataset=val_dataset,
    processing_class=tokenizer,
    compute_metrics=compute_metrics
)

trainer.train()

trainer.evaluate()

from sklearn.metrics import confusion_matrix
import numpy as np

preds = trainer.predict(val_dataset)
y_pred = np.argmax(preds.predictions, axis=1)

print(confusion_matrix(preds.label_ids, y_pred))

def predict(prompt):
    # Move inputs to the same device as the model
    inputs = tokenizer(prompt, return_tensors="pt", truncation=True, padding=True).to(model.device)
    outputs = model(**inputs)
    pred = outputs.logits.argmax(dim=1).item()
    return le.inverse_transform([pred])[0]

test_prompts = [
   ""
]

for p in test_prompts:
    print(f"Prompt: {p}")
    print(f"Prediction: {predict(p)}\n")

